name: first

on: push

jobs:
    job1:
        name: First Job
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - run: env | sort
    job2:
        name: Second Job
        runs-on: windows-latest
        steps:
          - uses: actions/checkout@v3
          - uses: "Get-ChildItem Env: | Sort-Object Name"
